// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hdfs.proto

package ds.hdfs;

public final class marshallstuff {
  private marshallstuff() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FileInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string filename = 1;
    /**
     * <code>optional string filename = 1;</code>
     */
    boolean hasFilename();
    /**
     * <code>optional string filename = 1;</code>
     */
    java.lang.String getFilename();
    /**
     * <code>optional string filename = 1;</code>
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    // optional uint32 filehandle = 2;
    /**
     * <code>optional uint32 filehandle = 2;</code>
     */
    boolean hasFilehandle();
    /**
     * <code>optional uint32 filehandle = 2;</code>
     */
    int getFilehandle();

    // optional bool writemode = 3;
    /**
     * <code>optional bool writemode = 3;</code>
     */
    boolean hasWritemode();
    /**
     * <code>optional bool writemode = 3;</code>
     */
    boolean getWritemode();

    // optional uint32 replication = 4;
    /**
     * <code>optional uint32 replication = 4;</code>
     */
    boolean hasReplication();
    /**
     * <code>optional uint32 replication = 4;</code>
     */
    int getReplication();

    // repeated string chunkList = 5;
    /**
     * <code>repeated string chunkList = 5;</code>
     */
    java.util.List<java.lang.String>
    getChunkListList();
    /**
     * <code>repeated string chunkList = 5;</code>
     */
    int getChunkListCount();
    /**
     * <code>repeated string chunkList = 5;</code>
     */
    java.lang.String getChunkList(int index);
    /**
     * <code>repeated string chunkList = 5;</code>
     */
    com.google.protobuf.ByteString
        getChunkListBytes(int index);
  }
  /**
   * Protobuf type {@code hdfs.FileInfo}
   */
  public static final class FileInfo extends
      com.google.protobuf.GeneratedMessage
      implements FileInfoOrBuilder {
    // Use FileInfo.newBuilder() to construct.
    private FileInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileInfo defaultInstance;
    public static FileInfo getDefaultInstance() {
      return defaultInstance;
    }

    public FileInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              filename_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              filehandle_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              writemode_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              replication_ = input.readUInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                chunkList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              chunkList_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          chunkList_ = new com.google.protobuf.UnmodifiableLazyStringList(chunkList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.hdfs.marshallstuff.internal_static_hdfs_FileInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.hdfs.marshallstuff.internal_static_hdfs_FileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.hdfs.marshallstuff.FileInfo.class, ds.hdfs.marshallstuff.FileInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<FileInfo> PARSER =
        new com.google.protobuf.AbstractParser<FileInfo>() {
      public FileInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string filename = 1;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private java.lang.Object filename_;
    /**
     * <code>optional string filename = 1;</code>
     */
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string filename = 1;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string filename = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 filehandle = 2;
    public static final int FILEHANDLE_FIELD_NUMBER = 2;
    private int filehandle_;
    /**
     * <code>optional uint32 filehandle = 2;</code>
     */
    public boolean hasFilehandle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 filehandle = 2;</code>
     */
    public int getFilehandle() {
      return filehandle_;
    }

    // optional bool writemode = 3;
    public static final int WRITEMODE_FIELD_NUMBER = 3;
    private boolean writemode_;
    /**
     * <code>optional bool writemode = 3;</code>
     */
    public boolean hasWritemode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool writemode = 3;</code>
     */
    public boolean getWritemode() {
      return writemode_;
    }

    // optional uint32 replication = 4;
    public static final int REPLICATION_FIELD_NUMBER = 4;
    private int replication_;
    /**
     * <code>optional uint32 replication = 4;</code>
     */
    public boolean hasReplication() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 replication = 4;</code>
     */
    public int getReplication() {
      return replication_;
    }

    // repeated string chunkList = 5;
    public static final int CHUNKLIST_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList chunkList_;
    /**
     * <code>repeated string chunkList = 5;</code>
     */
    public java.util.List<java.lang.String>
        getChunkListList() {
      return chunkList_;
    }
    /**
     * <code>repeated string chunkList = 5;</code>
     */
    public int getChunkListCount() {
      return chunkList_.size();
    }
    /**
     * <code>repeated string chunkList = 5;</code>
     */
    public java.lang.String getChunkList(int index) {
      return chunkList_.get(index);
    }
    /**
     * <code>repeated string chunkList = 5;</code>
     */
    public com.google.protobuf.ByteString
        getChunkListBytes(int index) {
      return chunkList_.getByteString(index);
    }

    private void initFields() {
      filename_ = "";
      filehandle_ = 0;
      writemode_ = false;
      replication_ = 0;
      chunkList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFilenameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, filehandle_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, writemode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, replication_);
      }
      for (int i = 0; i < chunkList_.size(); i++) {
        output.writeBytes(5, chunkList_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFilenameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, filehandle_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, writemode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, replication_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < chunkList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(chunkList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getChunkListList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ds.hdfs.marshallstuff.FileInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.hdfs.marshallstuff.FileInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.FileInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.hdfs.marshallstuff.FileInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.FileInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ds.hdfs.marshallstuff.FileInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.FileInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ds.hdfs.marshallstuff.FileInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.FileInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ds.hdfs.marshallstuff.FileInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ds.hdfs.marshallstuff.FileInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hdfs.FileInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ds.hdfs.marshallstuff.FileInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.hdfs.marshallstuff.internal_static_hdfs_FileInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.hdfs.marshallstuff.internal_static_hdfs_FileInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.hdfs.marshallstuff.FileInfo.class, ds.hdfs.marshallstuff.FileInfo.Builder.class);
      }

      // Construct using ds.hdfs.marshallstuff.FileInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        filename_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        filehandle_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        writemode_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        replication_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        chunkList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.hdfs.marshallstuff.internal_static_hdfs_FileInfo_descriptor;
      }

      public ds.hdfs.marshallstuff.FileInfo getDefaultInstanceForType() {
        return ds.hdfs.marshallstuff.FileInfo.getDefaultInstance();
      }

      public ds.hdfs.marshallstuff.FileInfo build() {
        ds.hdfs.marshallstuff.FileInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ds.hdfs.marshallstuff.FileInfo buildPartial() {
        ds.hdfs.marshallstuff.FileInfo result = new ds.hdfs.marshallstuff.FileInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filename_ = filename_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.filehandle_ = filehandle_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.writemode_ = writemode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.replication_ = replication_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          chunkList_ = new com.google.protobuf.UnmodifiableLazyStringList(
              chunkList_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.chunkList_ = chunkList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.hdfs.marshallstuff.FileInfo) {
          return mergeFrom((ds.hdfs.marshallstuff.FileInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.hdfs.marshallstuff.FileInfo other) {
        if (other == ds.hdfs.marshallstuff.FileInfo.getDefaultInstance()) return this;
        if (other.hasFilename()) {
          bitField0_ |= 0x00000001;
          filename_ = other.filename_;
          onChanged();
        }
        if (other.hasFilehandle()) {
          setFilehandle(other.getFilehandle());
        }
        if (other.hasWritemode()) {
          setWritemode(other.getWritemode());
        }
        if (other.hasReplication()) {
          setReplication(other.getReplication());
        }
        if (!other.chunkList_.isEmpty()) {
          if (chunkList_.isEmpty()) {
            chunkList_ = other.chunkList_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureChunkListIsMutable();
            chunkList_.addAll(other.chunkList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.hdfs.marshallstuff.FileInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.hdfs.marshallstuff.FileInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string filename = 1;
      private java.lang.Object filename_ = "";
      /**
       * <code>optional string filename = 1;</code>
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string filename = 1;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string filename = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string filename = 1;</code>
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 1;</code>
       */
      public Builder clearFilename() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 1;</code>
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
        return this;
      }

      // optional uint32 filehandle = 2;
      private int filehandle_ ;
      /**
       * <code>optional uint32 filehandle = 2;</code>
       */
      public boolean hasFilehandle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 filehandle = 2;</code>
       */
      public int getFilehandle() {
        return filehandle_;
      }
      /**
       * <code>optional uint32 filehandle = 2;</code>
       */
      public Builder setFilehandle(int value) {
        bitField0_ |= 0x00000002;
        filehandle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 filehandle = 2;</code>
       */
      public Builder clearFilehandle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        filehandle_ = 0;
        onChanged();
        return this;
      }

      // optional bool writemode = 3;
      private boolean writemode_ ;
      /**
       * <code>optional bool writemode = 3;</code>
       */
      public boolean hasWritemode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool writemode = 3;</code>
       */
      public boolean getWritemode() {
        return writemode_;
      }
      /**
       * <code>optional bool writemode = 3;</code>
       */
      public Builder setWritemode(boolean value) {
        bitField0_ |= 0x00000004;
        writemode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool writemode = 3;</code>
       */
      public Builder clearWritemode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        writemode_ = false;
        onChanged();
        return this;
      }

      // optional uint32 replication = 4;
      private int replication_ ;
      /**
       * <code>optional uint32 replication = 4;</code>
       */
      public boolean hasReplication() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 replication = 4;</code>
       */
      public int getReplication() {
        return replication_;
      }
      /**
       * <code>optional uint32 replication = 4;</code>
       */
      public Builder setReplication(int value) {
        bitField0_ |= 0x00000008;
        replication_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 replication = 4;</code>
       */
      public Builder clearReplication() {
        bitField0_ = (bitField0_ & ~0x00000008);
        replication_ = 0;
        onChanged();
        return this;
      }

      // repeated string chunkList = 5;
      private com.google.protobuf.LazyStringList chunkList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureChunkListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          chunkList_ = new com.google.protobuf.LazyStringArrayList(chunkList_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string chunkList = 5;</code>
       */
      public java.util.List<java.lang.String>
          getChunkListList() {
        return java.util.Collections.unmodifiableList(chunkList_);
      }
      /**
       * <code>repeated string chunkList = 5;</code>
       */
      public int getChunkListCount() {
        return chunkList_.size();
      }
      /**
       * <code>repeated string chunkList = 5;</code>
       */
      public java.lang.String getChunkList(int index) {
        return chunkList_.get(index);
      }
      /**
       * <code>repeated string chunkList = 5;</code>
       */
      public com.google.protobuf.ByteString
          getChunkListBytes(int index) {
        return chunkList_.getByteString(index);
      }
      /**
       * <code>repeated string chunkList = 5;</code>
       */
      public Builder setChunkList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChunkListIsMutable();
        chunkList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string chunkList = 5;</code>
       */
      public Builder addChunkList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChunkListIsMutable();
        chunkList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string chunkList = 5;</code>
       */
      public Builder addAllChunkList(
          java.lang.Iterable<java.lang.String> values) {
        ensureChunkListIsMutable();
        super.addAll(values, chunkList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string chunkList = 5;</code>
       */
      public Builder clearChunkList() {
        chunkList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string chunkList = 5;</code>
       */
      public Builder addChunkListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChunkListIsMutable();
        chunkList_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hdfs.FileInfo)
    }

    static {
      defaultInstance = new FileInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hdfs.FileInfo)
  }

  public interface IPOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string ip = 1;
    /**
     * <code>optional string ip = 1;</code>
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 1;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();
  }
  /**
   * Protobuf type {@code hdfs.IP}
   *
   * <pre>
   * Part 2
   * </pre>
   */
  public static final class IP extends
      com.google.protobuf.GeneratedMessage
      implements IPOrBuilder {
    // Use IP.newBuilder() to construct.
    private IP(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IP(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IP defaultInstance;
    public static IP getDefaultInstance() {
      return defaultInstance;
    }

    public IP getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IP(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              ip_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.hdfs.marshallstuff.internal_static_hdfs_IP_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.hdfs.marshallstuff.internal_static_hdfs_IP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.hdfs.marshallstuff.IP.class, ds.hdfs.marshallstuff.IP.Builder.class);
    }

    public static com.google.protobuf.Parser<IP> PARSER =
        new com.google.protobuf.AbstractParser<IP>() {
      public IP parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IP(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IP> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string ip = 1;
    public static final int IP_FIELD_NUMBER = 1;
    private java.lang.Object ip_;
    /**
     * <code>optional string ip = 1;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string ip = 1;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      ip_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIpBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIpBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ds.hdfs.marshallstuff.IP parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.hdfs.marshallstuff.IP parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.IP parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.hdfs.marshallstuff.IP parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.IP parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ds.hdfs.marshallstuff.IP parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.IP parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ds.hdfs.marshallstuff.IP parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.IP parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ds.hdfs.marshallstuff.IP parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ds.hdfs.marshallstuff.IP prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hdfs.IP}
     *
     * <pre>
     * Part 2
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ds.hdfs.marshallstuff.IPOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.hdfs.marshallstuff.internal_static_hdfs_IP_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.hdfs.marshallstuff.internal_static_hdfs_IP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.hdfs.marshallstuff.IP.class, ds.hdfs.marshallstuff.IP.Builder.class);
      }

      // Construct using ds.hdfs.marshallstuff.IP.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.hdfs.marshallstuff.internal_static_hdfs_IP_descriptor;
      }

      public ds.hdfs.marshallstuff.IP getDefaultInstanceForType() {
        return ds.hdfs.marshallstuff.IP.getDefaultInstance();
      }

      public ds.hdfs.marshallstuff.IP build() {
        ds.hdfs.marshallstuff.IP result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ds.hdfs.marshallstuff.IP buildPartial() {
        ds.hdfs.marshallstuff.IP result = new ds.hdfs.marshallstuff.IP(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ip_ = ip_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.hdfs.marshallstuff.IP) {
          return mergeFrom((ds.hdfs.marshallstuff.IP)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.hdfs.marshallstuff.IP other) {
        if (other == ds.hdfs.marshallstuff.IP.getDefaultInstance()) return this;
        if (other.hasIp()) {
          bitField0_ |= 0x00000001;
          ip_ = other.ip_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.hdfs.marshallstuff.IP parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.hdfs.marshallstuff.IP) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string ip = 1;
      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 1;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 1;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ip_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hdfs.IP)
    }

    static {
      defaultInstance = new IP(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hdfs.IP)
  }

  public interface IPListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .hdfs.IP address = 1;
    /**
     * <code>repeated .hdfs.IP address = 1;</code>
     */
    java.util.List<ds.hdfs.marshallstuff.IP> 
        getAddressList();
    /**
     * <code>repeated .hdfs.IP address = 1;</code>
     */
    ds.hdfs.marshallstuff.IP getAddress(int index);
    /**
     * <code>repeated .hdfs.IP address = 1;</code>
     */
    int getAddressCount();
    /**
     * <code>repeated .hdfs.IP address = 1;</code>
     */
    java.util.List<? extends ds.hdfs.marshallstuff.IPOrBuilder> 
        getAddressOrBuilderList();
    /**
     * <code>repeated .hdfs.IP address = 1;</code>
     */
    ds.hdfs.marshallstuff.IPOrBuilder getAddressOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code hdfs.IPList}
   */
  public static final class IPList extends
      com.google.protobuf.GeneratedMessage
      implements IPListOrBuilder {
    // Use IPList.newBuilder() to construct.
    private IPList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IPList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IPList defaultInstance;
    public static IPList getDefaultInstance() {
      return defaultInstance;
    }

    public IPList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IPList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                address_ = new java.util.ArrayList<ds.hdfs.marshallstuff.IP>();
                mutable_bitField0_ |= 0x00000001;
              }
              address_.add(input.readMessage(ds.hdfs.marshallstuff.IP.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          address_ = java.util.Collections.unmodifiableList(address_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.hdfs.marshallstuff.internal_static_hdfs_IPList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.hdfs.marshallstuff.internal_static_hdfs_IPList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.hdfs.marshallstuff.IPList.class, ds.hdfs.marshallstuff.IPList.Builder.class);
    }

    public static com.google.protobuf.Parser<IPList> PARSER =
        new com.google.protobuf.AbstractParser<IPList>() {
      public IPList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IPList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IPList> getParserForType() {
      return PARSER;
    }

    // repeated .hdfs.IP address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private java.util.List<ds.hdfs.marshallstuff.IP> address_;
    /**
     * <code>repeated .hdfs.IP address = 1;</code>
     */
    public java.util.List<ds.hdfs.marshallstuff.IP> getAddressList() {
      return address_;
    }
    /**
     * <code>repeated .hdfs.IP address = 1;</code>
     */
    public java.util.List<? extends ds.hdfs.marshallstuff.IPOrBuilder> 
        getAddressOrBuilderList() {
      return address_;
    }
    /**
     * <code>repeated .hdfs.IP address = 1;</code>
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated .hdfs.IP address = 1;</code>
     */
    public ds.hdfs.marshallstuff.IP getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <code>repeated .hdfs.IP address = 1;</code>
     */
    public ds.hdfs.marshallstuff.IPOrBuilder getAddressOrBuilder(
        int index) {
      return address_.get(index);
    }

    private void initFields() {
      address_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < address_.size(); i++) {
        output.writeMessage(1, address_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < address_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, address_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ds.hdfs.marshallstuff.IPList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.hdfs.marshallstuff.IPList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.IPList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.hdfs.marshallstuff.IPList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.IPList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ds.hdfs.marshallstuff.IPList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.IPList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ds.hdfs.marshallstuff.IPList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ds.hdfs.marshallstuff.IPList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ds.hdfs.marshallstuff.IPList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ds.hdfs.marshallstuff.IPList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hdfs.IPList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ds.hdfs.marshallstuff.IPListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.hdfs.marshallstuff.internal_static_hdfs_IPList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.hdfs.marshallstuff.internal_static_hdfs_IPList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.hdfs.marshallstuff.IPList.class, ds.hdfs.marshallstuff.IPList.Builder.class);
      }

      // Construct using ds.hdfs.marshallstuff.IPList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          addressBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.hdfs.marshallstuff.internal_static_hdfs_IPList_descriptor;
      }

      public ds.hdfs.marshallstuff.IPList getDefaultInstanceForType() {
        return ds.hdfs.marshallstuff.IPList.getDefaultInstance();
      }

      public ds.hdfs.marshallstuff.IPList build() {
        ds.hdfs.marshallstuff.IPList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ds.hdfs.marshallstuff.IPList buildPartial() {
        ds.hdfs.marshallstuff.IPList result = new ds.hdfs.marshallstuff.IPList(this);
        int from_bitField0_ = bitField0_;
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            address_ = java.util.Collections.unmodifiableList(address_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.hdfs.marshallstuff.IPList) {
          return mergeFrom((ds.hdfs.marshallstuff.IPList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.hdfs.marshallstuff.IPList other) {
        if (other == ds.hdfs.marshallstuff.IPList.getDefaultInstance()) return this;
        if (addressBuilder_ == null) {
          if (!other.address_.isEmpty()) {
            if (address_.isEmpty()) {
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAddressIsMutable();
              address_.addAll(other.address_);
            }
            onChanged();
          }
        } else {
          if (!other.address_.isEmpty()) {
            if (addressBuilder_.isEmpty()) {
              addressBuilder_.dispose();
              addressBuilder_ = null;
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000001);
              addressBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAddressFieldBuilder() : null;
            } else {
              addressBuilder_.addAllMessages(other.address_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.hdfs.marshallstuff.IPList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.hdfs.marshallstuff.IPList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .hdfs.IP address = 1;
      private java.util.List<ds.hdfs.marshallstuff.IP> address_ =
        java.util.Collections.emptyList();
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          address_ = new java.util.ArrayList<ds.hdfs.marshallstuff.IP>(address_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ds.hdfs.marshallstuff.IP, ds.hdfs.marshallstuff.IP.Builder, ds.hdfs.marshallstuff.IPOrBuilder> addressBuilder_;

      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public java.util.List<ds.hdfs.marshallstuff.IP> getAddressList() {
        if (addressBuilder_ == null) {
          return java.util.Collections.unmodifiableList(address_);
        } else {
          return addressBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public int getAddressCount() {
        if (addressBuilder_ == null) {
          return address_.size();
        } else {
          return addressBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public ds.hdfs.marshallstuff.IP getAddress(int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);
        } else {
          return addressBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public Builder setAddress(
          int index, ds.hdfs.marshallstuff.IP value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.set(index, value);
          onChanged();
        } else {
          addressBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public Builder setAddress(
          int index, ds.hdfs.marshallstuff.IP.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public Builder addAddress(ds.hdfs.marshallstuff.IP value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(value);
          onChanged();
        } else {
          addressBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public Builder addAddress(
          int index, ds.hdfs.marshallstuff.IP value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(index, value);
          onChanged();
        } else {
          addressBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public Builder addAddress(
          ds.hdfs.marshallstuff.IP.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public Builder addAddress(
          int index, ds.hdfs.marshallstuff.IP.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public Builder addAllAddress(
          java.lang.Iterable<? extends ds.hdfs.marshallstuff.IP> values) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          super.addAll(values, address_);
          onChanged();
        } else {
          addressBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public Builder removeAddress(int index) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.remove(index);
          onChanged();
        } else {
          addressBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public ds.hdfs.marshallstuff.IP.Builder getAddressBuilder(
          int index) {
        return getAddressFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public ds.hdfs.marshallstuff.IPOrBuilder getAddressOrBuilder(
          int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);  } else {
          return addressBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public java.util.List<? extends ds.hdfs.marshallstuff.IPOrBuilder> 
           getAddressOrBuilderList() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(address_);
        }
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public ds.hdfs.marshallstuff.IP.Builder addAddressBuilder() {
        return getAddressFieldBuilder().addBuilder(
            ds.hdfs.marshallstuff.IP.getDefaultInstance());
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public ds.hdfs.marshallstuff.IP.Builder addAddressBuilder(
          int index) {
        return getAddressFieldBuilder().addBuilder(
            index, ds.hdfs.marshallstuff.IP.getDefaultInstance());
      }
      /**
       * <code>repeated .hdfs.IP address = 1;</code>
       */
      public java.util.List<ds.hdfs.marshallstuff.IP.Builder> 
           getAddressBuilderList() {
        return getAddressFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ds.hdfs.marshallstuff.IP, ds.hdfs.marshallstuff.IP.Builder, ds.hdfs.marshallstuff.IPOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ds.hdfs.marshallstuff.IP, ds.hdfs.marshallstuff.IP.Builder, ds.hdfs.marshallstuff.IPOrBuilder>(
                  address_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:hdfs.IPList)
    }

    static {
      defaultInstance = new IPList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hdfs.IPList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hdfs_FileInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hdfs_FileInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hdfs_IP_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hdfs_IP_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hdfs_IPList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hdfs_IPList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhdfs.proto\022\004hdfs\"k\n\010FileInfo\022\020\n\010filena" +
      "me\030\001 \001(\t\022\022\n\nfilehandle\030\002 \001(\r\022\021\n\twritemod" +
      "e\030\003 \001(\010\022\023\n\013replication\030\004 \001(\r\022\021\n\tchunkLis" +
      "t\030\005 \003(\t\"\020\n\002IP\022\n\n\002ip\030\001 \001(\t\"#\n\006IPList\022\031\n\007a" +
      "ddress\030\001 \003(\0132\010.hdfs.IPB\030\n\007ds.hdfsB\rmarsh" +
      "allstuff"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hdfs_FileInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hdfs_FileInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hdfs_FileInfo_descriptor,
              new java.lang.String[] { "Filename", "Filehandle", "Writemode", "Replication", "ChunkList", });
          internal_static_hdfs_IP_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_hdfs_IP_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hdfs_IP_descriptor,
              new java.lang.String[] { "Ip", });
          internal_static_hdfs_IPList_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_hdfs_IPList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hdfs_IPList_descriptor,
              new java.lang.String[] { "Address", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
